# Generated by Django 5.0.2 on 2024-02-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
