# Generated by Django 5.0.2 on 2024-03-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_app", "0002_alter_postmedia_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/%Y/%m/%d/"),
        ),
    ]
